"""initial_schema

Revision ID: c7901baaee6f
Revises: 
Create Date: 2026-09-19 16:08:44.891889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7901baaee6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_athletes_email'), 'athletes', ['email'], unique=True)
    op.create_index(op.f('ix_athletes_id'), 'athletes', ['id'], unique=False)
    op.create_table('athlete_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('sport', sa.String(), nullable=False),
    sa.Column('discipline', sa.String(), nullable=True),
    sa.Column('primary_role', sa.String(), nullable=True),
    sa.Column('sub_role', sa.String(), nullable=True),
    sa.Column('secondary_role', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('development_objectives', sa.JSON(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('training_days_per_week', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Integer(), nullable=False),
    sa.Column('self_assessment_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('athlete_id')
    )
    op.create_index(op.f('ix_athlete_profiles_id'), 'athlete_profiles', ['id'], unique=False)
    op.create_table('movement_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.String(), nullable=True),
    sa.Column('video_filename', sa.String(), nullable=False),
    sa.Column('video_path', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_movement_quality', sa.Float(), nullable=True),
    sa.Column('pose_data', sa.JSON(), nullable=True),
    sa.Column('movement_scores', sa.JSON(), nullable=True),
    sa.Column('metric_details', sa.JSON(), nullable=True),
    sa.Column('movement_feedback', sa.JSON(), nullable=True),
    sa.Column('quality_report', sa.JSON(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movement_assessments_id'), 'movement_assessments', ['id'], unique=False)
    op.create_table('bottleneck_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=True),
    sa.Column('bottlenecks', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('proficient', sa.JSON(), nullable=True),
    sa.Column('development_areas', sa.JSON(), nullable=True),
    sa.Column('critical_bottlenecks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['movement_assessments.id'], ),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bottleneck_reports_id'), 'bottleneck_reports', ['id'], unique=False)
    op.create_table('training_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('bottleneck_report_id', sa.Integer(), nullable=True),
    sa.Column('plan_data', sa.JSON(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['bottleneck_report_id'], ['bottleneck_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_plans_id'), 'training_plans', ['id'], unique=False)
    op.create_table('progress_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('perceived_exertion', sa.Integer(), nullable=False),
    sa.Column('workload_index', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('exercises_completed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['training_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_logs_id'), 'progress_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_progress_logs_id'), table_name='progress_logs')
    op.drop_table('progress_logs')
    op.drop_index(op.f('ix_training_plans_id'), table_name='training_plans')
    op.drop_table('training_plans')
    op.drop_index(op.f('ix_bottleneck_reports_id'), table_name='bottleneck_reports')
    op.drop_table('bottleneck_reports')
    op.drop_index(op.f('ix_movement_assessments_id'), table_name='movement_assessments')
    op.drop_table('movement_assessments')
    op.drop_index(op.f('ix_athlete_profiles_id'), table_name='athlete_profiles')
    op.drop_table('athlete_profiles')
    op.drop_index(op.f('ix_athletes_id'), table_name='athletes')
    op.drop_index(op.f('ix_athletes_email'), table_name='athletes')
    op.drop_table('athletes')
    # ### end Alembic commands ###
